### ISSUE TITLE
Momentum scrolling

### ISSUE THREAD

**Issue by awatson1978** [clinical-meteor/meteor-on-fhir#1]
Need to enable momentum scrolling.  Possible solutions:

**CSS Class**  

``` css
.scrollable{
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;

}
```

**React Mixin**  
https://gist.github.com/chestozo/0d28facf5a28509d4210

Note:  this feature may benefit from an isolated example. That is, instead of working within the meteor-on-fhir repo, it may help to start with a blank slate or the Meteor Chef Base project, and get momentum scrolling working with React and React-Toolbox without the distraction of the forums, weblog, patients, practitioners, etc.
